### ISSUE TITLE
Clarify what it means to not be compatible with the web interface

### ISSUE THREAD

**Issue by mwberry** [archivy/archivy-git#1]
The README.md says:

> The plugin is not yet compatible with the web interface.

I'm not quite understanding what that means. Does that mean that edits made from the web interface do not produce git commits? Is that not what the hook is doing? Or does this just mean that there is no UI for viewing the git DAG?

**Comment by Uzay-G** [comment]
Oh no if you've set up the hook, edits from the web interface will work and sync to the git repo.

However, Archivy also provides the `/plugins` page to basically run commands from plugins through the web interface, like `archivy git push` etc...

These won't work but setting up the hook will sync changes perfectly through the web interface!

**Comment by mwberry** [comment]
Ok. I only just now found the plugins page so it makes more sense. Will play around with this more next time I get a free moment. It seems like [git LFS](https://github.com/git-lfs/git-lfs) would be very beneficial. A cursory search suggests the git library you're using might not support it. If not, would you be open to shelling out to command-line git?

**Comment by Uzay-G** [comment]
You can actually also use `git` directly if you'd like, you just have to navigate to the directory where data is being stored and use git from there.
